// Import generate_commands function from library/Commands
const { generate_commands } = require("./library/Commands");

// Object containing commands and their descriptions
const CommandsIntent = {
  update: {
    description: "Send a manual notification to officers!",
  },
  help: {
    description: "If you need help to link your notion to discord!",
  },
  credits: {
    description: "The original authors of the bot",
  },
  adduser: {
    description: "Add a User to the Database",
  },
  getusers: {
    description: "Get a list of the users in the database",
  },
  initiate: {
    description: "Initiate the server for Notion Deadline Reminders.",
  },
  getdeadlines: {
    description: "Get your deadlines from the Notion Dashboard",
  }
};

// Export the commands generated by the generate_commands() function, passing in the CommandsIntent object
module.exports = generate_commands(CommandsIntent);
